### ISSUE TITLE
Cannot run the yo slimphp

### ISSUE THREAD

**Issue by lironsher** [zguillez/generator-slimphp#1]
$ sudo npm install -g generator-slimphp
/Users/User/.nvm/versions/node/v5.2.0/lib
└── generator-slimphp@0.1.8 

$ yo slimphp
Error slimphp 

You don't seem to have a generator with the name slimphp installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 26 registered generators run yo with the `--help` option.

**Comment by zguillez** [comment]
Hi! Try to unistall the generator and install again, please
and update node, npm and yo if is necesary
I tested installing the generator and I don´t get any problem

I run:

$ sudo npm un -g generator-slimphp
$ sudo npm i -g generator-slimphp
$ ./composer.phar install
** edit the config.php for database connect **
$ grunt serve

![image](https://cloud.githubusercontent.com/assets/2631152/12266503/ce9872e2-b943-11e5-9230-84fb537b1886.png)

And the generator runs OK

![image](https://cloud.githubusercontent.com/assets/2631152/12266630/716d6edc-b944-11e5-9114-33eca6dc88a2.png)

Tell me if you still have the issue
