### ISSUE TITLE
Method DELETE Error

### ISSUE THREAD

**Issue by virushcode** [zguillez/generator-slimphp#3]
slimframework have 4 method get, post, put, delete.
i use this method delete and i found an error "Method not allowed. Must be one of: GET (405)"
please give me solution sir :smile:

**Comment by sirbabyface** [comment]
This is a problem with your HTTP server, that might not allow that method. Check your server settings to allow all the methods. I had in the past similar problems with an IIS server.

**Comment by zguillez** [comment]
Try to edit the file **function route** in file **app.php** to allow this methods:

```
public function route($route, $method, $callback)
		{
			if ($method === 'POST') {
				$this->app->post($route, $callback);
			} else if ($method === 'GET') {
				$this->app->get($route, $callback);
			} else if ($method === 'PUT') {
				$this->app->put($route, $callback);
			} else if ($method === 'DELETE') {
				$this->app->delete($route, $callback);
			}
		}
```

Then you can add this methods to your routes paths in file **index.php**:

```
$api->route('/test1', 'PUT', require 'inc/routes/test1.php');
$api->route('/test2', 'DELETE', require 'inc/routes/test2.php');
```

I will update the code of the generator asap

**Comment by zguillez** [comment]
I updated the generator to v1.1.1

**Comment by virushcode** [comment]
@zguillez thanks..
